// French translations. The key is the English text used in the app.
export default {
  // Navigation & shell
  Schedule: 'Planning',
  Inventory: 'Stock',
  'My calendar': 'Mon agenda',
  Admin: 'Admin',
  'Sign out': 'Se déconnecter',
  'Change password': 'Changer le mot de passe',
  'Your password has been changed.': 'Votre mot de passe a été modifié.',
  'Save password': 'Enregistrer le mot de passe',
  'New password': 'Nouveau mot de passe',
  'At least 8 characters.': 'Au moins 8 caractères.',
  'Loading…': 'Chargement…',
  'Something went wrong.': 'Une erreur est survenue.',
  Retry: 'Réessayer',
  Dismiss: 'Fermer',
  Cancel: 'Annuler',
  Close: 'Fermer',
  Save: 'Enregistrer',
  Add: 'Ajouter',
  Remove: 'Retirer',
  Edit: 'Modifier',
  never: 'jamais',
  'No access yet': "Pas encore d'accès",
  "{email} isn't on the staff list. Ask an admin to add this address, then sign in again.":
    "{email} ne figure pas dans la liste de l'équipe. Demandez à un admin d'ajouter cette adresse, puis reconnectez-vous.",

  // Login
  'Sign in': 'Connexion',
  Email: 'E-mail',
  Password: 'Mot de passe',
  'Please wait…': 'Veuillez patienter…',
  'Forgot password?': 'Mot de passe oublié ?',
  'Back to sign in': 'Retour à la connexion',
  'Reset your password': 'Réinitialiser votre mot de passe',
  'Email me a reset link': 'Envoyer un lien de réinitialisation',
  'If {email} has an account, a reset link is on its way.':
    'Si {email} a un compte, un lien de réinitialisation est en route.',
  "Accounts are created by an admin. Ask one if you don't have yours yet.":
    "Les comptes sont créés par un admin. Demandez-en un si vous n'avez pas encore le vôtre.",
  'Choose your password': 'Choisissez votre mot de passe',
  'Saving…': 'Enregistrement…',

  // Schedule
  'This week': 'Cette semaine',
  "Who's on the counter": 'Qui est au comptoir',
  'Shifts open for cover, and the people whose calendars are free.':
    'Les créneaux à pourvoir, et les personnes dont l’agenda est libre.',
  'Add shift': 'Ajouter un créneau',
  'Edit shift': 'Modifier le créneau',
  'Delete shift': 'Supprimer le créneau',
  'Delete this shift?': 'Supprimer ce créneau ?',
  'No shifts yet. Add the first one.': 'Aucun créneau pour le moment. Ajoutez le premier.',
  'No shifts have been planned yet.': "Aucun créneau n'a encore été planifié.",
  '{n} open': '{n} à pourvoir',
  Full: 'Complet',
  '{a} of {b} staffed': '{a} sur {b} pourvu(s)',
  Busy: 'Occupé·e',
  'No classes': 'Pas de cours',
  'No classes that day: {names}.': 'Pas de cours ce jour-là : {names}.',
  'Availability is only a hint: it never decides who works a shift.':
    "La disponibilité est seulement indicative : elle ne décide jamais de qui travaille sur un créneau.",
  'Their calendar shows an event at this time': 'Son agenda indique un événement à ce moment',
  'Assign staff': "Affecter l'équipe",
  'Take shift': 'Prendre le créneau',
  'Leave shift': 'Quitter le créneau',
  Free: 'Libres',
  'No calendars connected yet': "Aucun agenda connecté pour l'instant",
  'Nobody is free': "Personne n'est libre",
  'Choose up to {n} people for this shift.': "Choisissez jusqu'à {n} personnes pour ce créneau.",
  'The shift must end after it starts.': 'Le créneau doit se terminer après son début.',
  Day: 'Jour',
  Starts: 'Début',
  Ends: 'Fin',
  'People needed': 'Personnes nécessaires',
  Monday: 'Lundi',
  Tuesday: 'Mardi',
  Wednesday: 'Mercredi',
  Thursday: 'Jeudi',
  Friday: 'Vendredi',
  Saturday: 'Samedi',
  Sunday: 'Dimanche',

  // Inventory
  'Stock room': 'Réserve',
  "What's on the shelf": "Ce qu'il y a en rayon",
  'Levels against the minimum, and what each item used this week.':
    'Les niveaux par rapport au minimum, et la consommation de chaque article cette semaine.',
  'Units in stock': 'Unités en stock',
  'Running low': 'Bientôt en rupture',
  'Used this week': 'Consommé cette semaine',
  'No products yet.': "Aucun produit pour l'instant.",
  'No products yet. Add some under Admin → Products.':
    "Aucun produit pour l'instant. Ajoutez-en dans Admin → Produits.",
  Item: 'Article',
  Level: 'Niveau',
  'In stock': 'En stock',
  Minimum: 'Minimum',
  Status: 'Statut',
  Low: 'Bas',
  OK: 'OK',
  Adjust: 'Ajuster',
  'Import stock': 'Importer le stock',
  Import: 'Importer',
  'SumUp items export (.csv)': 'Export des articles SumUp (.csv)',
  'Not a SumUp items export (columns "Item name" and "Quantity" are required).':
    'Ce fichier n’est pas un export d’articles SumUp (colonnes « Item name » et « Quantity » requises).',
  Updated: 'Mis à jour',
  New: 'Nouveaux',
  Ignored: 'Ignorés',
  'New products': 'Nouveaux produits',
  'Ignored: stock not tracked': 'Ignorés : stock non suivi',
  '{n} negative quantities will be set to 0.': '{n} quantités négatives seront mises à 0.',
  'Adjust {name}': 'Ajuster {name}',

  // Admin
  Setup: 'Configuration',
  'Team and menu': 'Équipe et carte',
  'Who can staff the café, what it sells, and which calendars feed the schedule.':
    'Qui peut tenir le café, ce qu’il vend, et quels agendas alimentent le planning.',
  Staff: 'Équipe',
  Products: 'Produits',
  Calendars: 'Agendas',
  Admins: 'Admins',
  'Add staff member': 'Ajouter un membre',
  'No staff members yet.': "Aucun membre pour l'instant.",
  'Make admin': 'Passer admin',
  'Make staff': 'Passer membre',
  'Send password link': 'Envoyer un lien de mot de passe',
  'Password link sent to {email}.': 'Lien de mot de passe envoyé à {email}.',
  'Send invitation': "Envoyer l'invitation",
  'Invitation sent to {email}. They choose their own password from the link.':
    'Invitation envoyée à {email}. La personne choisit elle-même son mot de passe depuis le lien.',
  'We email them a link to choose their own password, so nobody else ever sees it.':
    'Nous lui envoyons un lien pour choisir son propre mot de passe : personne d’autre ne le voit jamais.',
  Name: 'Nom',
  'Make this person an admin': 'Faire de cette personne un admin',
  'Add product': 'Ajouter un produit',
  'Product name': 'Nom du produit',
  'Cost per unit (€)': 'Coût unitaire (€)',
  'Selling price (€)': 'Prix de vente (€)',
  Cost: 'Coût',
  Price: 'Prix',
  'Connected calendars': 'Agendas connectés',
  'Each person connects their own calendar from “My calendar”. Only whether they are busy during a shift is used.':
    'Chaque personne connecte son agenda depuis « Mon agenda ». Seule sa disponibilité pendant un créneau est utilisée.',
  'Nobody has connected a calendar yet.': "Personne n'a encore connecté d'agenda.",
  'Last synced {date}': 'Dernière synchronisation : {date}',
  Connected: 'Connecté',
  Disconnect: 'Déconnecter',

  // My shifts in my calendar
  'My shifts in my calendar': 'Mes créneaux dans mon agenda',
  'Subscribe once and the shifts you are placed on show up in your calendar. The link lists your next shifts only.':
    'Abonnez-vous une fois : les créneaux sur lesquels vous êtes placé·e apparaissent dans votre agenda. Le lien ne liste que vos prochains créneaux.',
  'Your personal calendar address': 'Votre adresse d’agenda personnelle',
  'Add to Google Calendar': 'Ajouter à Google Agenda',
  'Copy address': "Copier l'adresse",
  Copied: 'Copié',
  'Copy failed. Select the address and copy it by hand.': "La copie a échoué. Sélectionnez l'adresse et copiez-la à la main.",
  'Reset link': 'Réinitialiser le lien',
  'Reset the link? The old one stops working and you will need to subscribe again.':
    "Réinitialiser le lien ? L'ancien cesse de fonctionner et vous devrez vous réabonner.",
  'Google refreshes subscribed calendars only every 12 to 24 hours, so a change can take that long to appear. Treat the address like a password.':
    "Google ne rafraîchit les agendas auxquels on est abonné que toutes les 12 à 24 heures : un changement peut mettre ce temps à apparaître. Traitez cette adresse comme un mot de passe.",

  // My calendar
  'Your availability': 'Votre disponibilité',
  'Connect your calendar and the schedule shows when you are free, and flags a shift that clashes with an event.':
    "Connectez votre agenda : le planning affiche quand vous êtes libre et signale un créneau qui chevauche un événement.",
  'Calendar connected': 'Agenda connecté',
  'Calendar connected.': 'Agenda connecté.',
  'Sync now': 'Synchroniser maintenant',
  'Use a different calendar': 'Utiliser un autre agenda',
  'Connect a calendar': 'Connecter un agenda',
  'In Google Calendar, open Settings and pick your calendar under “Settings for my calendars”.':
    'Dans Google Agenda, ouvrez les paramètres et choisissez votre agenda sous « Paramètres de mes agendas ».',
  'Scroll to “Integrate calendar” and copy the “Secret address in iCal format”.':
    'Descendez jusqu’à « Intégrer l’agenda » et copiez l’« Adresse secrète au format iCal ».',
  'Paste it below. We only read whether you are busy; event titles are never stored.':
    'Collez-la ci-dessous. Nous lisons seulement si vous êtes occupé·e ; les titres des événements ne sont jamais enregistrés.',
  'Secret iCal address': 'Adresse secrète iCal',
  Connect: 'Connecter',
  'Connecting…': 'Connexion…',
  'Treat the address like a password: anyone with it can read your calendar. You can reset it in Google Calendar at any time.':
    'Traitez cette adresse comme un mot de passe : toute personne qui la possède peut lire votre agenda. Vous pouvez la réinitialiser à tout moment dans Google Agenda.',
};
